### ISSUE TITLE
discord erro

### ISSUE THREAD

**Issue by rockoj** [Gabolicious/MonopolyBot#4] opened 2020-10-27 08:12 UTC
the app at times doesn't connect to the discord api they are asking for the latest code discord.js v12 if you can update it please.

**Comment by nxvvvv** [comment] 2020-11-13 05:44
yes pls upgrade it to discord js v12

**Comment by gabotaco** [comment] 2021-06-24 18:13
duplicate of https://github.com/Gabolicious/WealthyWumpus/issues/3

**Closed as completed by gabotaco** 2021-06-24 18:13 UTC
